export DOTFILES_PATH="/Users/cmoreno/.dotfiles"
export DOTLY_PATH="$DOTFILES_PATH/modules/dotly"
export DOTLY_THEME="codely"
export ZIM_HOME="$DOTFILES_PATH/shell/zsh/.zim"
export _EZA_PARAMS="--git --group-directories-first --time-style=long-iso --color-scale=all --icons"
