# --- Named sessions ---

[[session]]
name = "vault"
path = "~/Code/_vault"
startup_command = "source ~/.dotfiles/terminal/sesh/scripts/vault.sh"

[[session]]
name = "apprecio"
path = "~/Code/_vault"
startup_command = "source ~/.dotfiles/terminal/sesh/scripts/apprecio.sh"
